### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by mtitze**
A (speed) improved version to compute the case of unequal emittances.

Emittances should now be given as lists in the arguments (see examples/da_interactive.ipynb).

### CODE REVIEW

**Comment by rdemaria** [comment]
I missed the point of sixdb.py. Can't you import sixdeskdb in the notebook?

**Comment by mtitze** [comment]
Importing sixdb in the notebook worked for me only if I add .py, otherwise it did not recognized the file as python script.

**Comment by rdemaria** [comment]
Clear, but why do you need to import sixdb and not sixdeskdb?

**Comment by mtitze** [comment]
I can do that, but in this case I would use (or prefer the use of) a new function instead of RunDaVsTurns in order to avoid managing unused parameters.

If you want, I can create a new version of RunDaVsTurns to suite the new emittance options/calculations and we keep the original Python3 version for backwards compatibility.

**Comment by rdemaria** [comment]
Ok. In principle sixdb should only be an helper script and should not contain physics

**Comment by mtitze** [comment]
The latest commit should be backwards compatible to the methods in the first 2to3 branch now.

**Pull request merged**
