### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by mtitze**

### CODE REVIEW

**Comment by rdemaria** [comment]
shall I merge?

**Comment by mtitze** [comment]
It should only affect the part I am working on, so feel free to do it if you don't see any conflicts.

I am handling the emitx and emity from SixTrack later in my scripts where the DA is calculated. That's why I had to change the loading of the SQL files.

**Comment by rdemaria** [comment]
Ok,  i will merge then...

**Comment by mtitze** [comment]
I've made a small cleanup of comments

**Pull request merged**
